---
# Install the base operating system requirements for running Galaxy

- include: system_users.yml
  when: add_system_users

- include: ubuntu/packages.yml
  when: install_packages and ansible_distribution == 'Ubuntu'

- include: ubuntu/rabbitmq.yml
  when: install_rabbitmq and ((ansible_distribution == 'Ubuntu') or (ansible_distribution == 'Debian'))  # Works on Ubuntu and Debian

- include: ubuntu/docker.yml
  when: configure_docker and ansible_distribution == 'Ubuntu'

- include: debian/packages.yml
  when: install_packages and ansible_distribution == 'Debian'

- include: debian/docker.yml
  when: configure_docker and ansible_distribution == 'Debian'

- include: centos/packages.yml
  when: install_packages and ansible_distribution == 'CentOS'
